Developing schedule service.
bmstu-iu8-g4-2020-project/todo_web_service pull request #5
Opened 2020-11-04 15:55 UTC by aaaaaaaalesha

2020-11-12 13:36 UTC, dankokin requested changes
в общем, надо пройтись по коду, пересмотреть статус коды, исправить замечания, добавить валидацию

2020-11-12 13:36 UTC, dankokin commented on src/services/schedule_service.go
> +	var weekDays = map[string]time.Weekday{
может быть switch?)

2020-11-12 13:36 UTC, dankokin commented on src/services/schedule_service.go
> +	var weekDays = map[int]time.Weekday{
аналогично

2020-11-12 13:36 UTC, dankokin commented on src/services/schedule_service.go
> +	var weekDays = map[time.Weekday]string{
ну ты понял

2020-11-12 13:36 UTC, dankokin commented on src/services/schedule_service.go
> +		return []models.ScheduleTask{}, err
вместо пустого массива можно nil возращать

2020-11-12 13:36 UTC, dankokin commented on src/services/schedule_service.go
> +	fmt.Println(result.RowsAffected())
лишнее убрать

2020-11-12 13:36 UTC, dankokin commented on src/telegram_bot/schedule/schedule.go
> +	for i, scheduleTask := range weekdaySchedule {
попробуй https://golang.org/pkg/strings/#Builder так вроде быстрее

2020-11-12 13:36 UTC, dankokin commented on src/telegram_bot/user/user.go
> +func InitUser(userId int, userName string) error {
может сделать эти функции методами структуры юзера?

2020-11-12 14:53 UTC, aaaaaaaalesha commented on src/handlers/schedule_handlers.go
> +	fmt.Println("В меня вошли!")
ой, забыл убрать

2020-11-12 14:54 UTC, aaaaaaaalesha commented on src/handlers/schedule_handlers.go
> +	fmt.Println("Из меня вышли без ошибок!")
))))))))))

2020-11-12 15:05 UTC, aaaaaaaalesha commented on src/database/init_db.sql
> +    end_time time
А зачем? У нас время конкретно в расписаниях несёт больше значение для отображения, чем для какой-то логики.
Если мы будем хранить время с часовым поясом и тд, мы это просто никак не используем.
По сути это время даже не привязано к какому-то дню, а сравниваются между собой `start_time` и `end_time` для сортировки только. Чтобы найти какой-то duration, если понадобится, тоже этого вполне хватит.

2020-11-13 14:08 UTC, dankokin requested changes

2020-11-13 14:08 UTC, dankokin commented on src/handlers/schedule_handlers.go
> +func ValidateScheduleId(schIdStr string) (int, error) {
У тебя три одинкаовые функции, проверяющие int, оставь одну

2020-11-13 14:08 UTC, dankokin commented on src/services/schedule_service.go
> +	case "Понедельник":
``` 
case "Monday", "Понедельник":
    return time.Monday, nil
```

2020-11-13 14:08 UTC, dankokin commented on src/services/schedule_service.go
> +	return ""
в ```default```

2020-11-13 14:11 UTC, aaaaaaaalesha commented on src/handlers/schedule_handlers.go
> +func ValidateScheduleId(schIdStr string) (int, error) {
но по-разному же проверяют(

2020-11-13 16:19 UTC, dankokin commented on src/handlers/schedule_handlers.go
> +func ValidateScheduleId(schIdStr string) (int, error) {
У них минимальные отличия, можно свести к одной функции

2020-11-13 19:52 UTC, aaaaaaaalesha commented on src/services/schedule_service.go
> +	case "Понедельник":
![](http://memesmix.net/media/created/603xbw.jpg)

2020-11-15 16:07 UTC, sergejkoll approved these changes

2020-11-15 16:22 UTC, merged